---
  swagger: "2.0"
  info: 
    description: "This is an example for you to look up do another. This Example includes:Login and Fund Transfer"
    version: "1.0.0"
    title: "Api Example"
    termsOfService: "http://swagger.io/terms/"
    contact: 
      email: "jist@com.vn"
    license: 
      name: "Apache 2.0"
      url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  host: "example.io"
  basePath: "/v2"
  schemes: 
    - "https"
    - "http"
  security: 
    - 
      default: []
  paths: 
    /login: 
      post: 
        tags:
          - Login
        summary: Login Example 
        description: Returns a session id
        operationId: username,password
        parameters: 
          - 
            in: "body"
            name: "Payload"
            description: "Request Body"
            required: false
            summary: Login Example
            schema: 
              type: "object"
              properties: 
                USERNAME: 
                  type: "string"
                  example: "usrname"
                PASSWORD: 
                  type: "string"
                  example: "password"
        responses: 
          200: 
            description: "OK"
        security: 
          - 
            default: 
              - "LoginAndFTF"
        x-auth-type: "Application & Application User"
        x-throttling-tier: "Unlimited"
    /MB0010: 
      post: 
        tags:
          - MB0010
        summary: MB0010 
        description: Returns a 
        operationId: username,password
        parameters: 
          - 
            in: "body"
            name: "Payload"
            description: "Request Body"
            required: false
            schema: 
              type: "object"
              properties: 
                SESSIONID: 
                  type: "string"
                  example: "00000171-a18e-1102-0000-0171a18e110b"
                CREDITACC: 
                  type: "string"
                  example: "000000081"
                DEBITACC: 
                  type: "string"
                  example: "000000082"
                AMT: 
                  type: "string"
                  example: "10"
                DEBITFEE: 
                  type: "string"
                  example: "0"
                CREDITFEE: 
                  type: "string"
                  example: "0"
                FEEACC: 
                  type: "string"
                  example: "14080129650212"
                ID: 
                  type: "string"
                  example: "BHD00009"
                DESCS: 
                  type: "string"
                  example: "Funds Transfer!"
        responses: 
          200: 
            description: "OK"
        security: 
          - 
            default: 
              - "LoginAndFTF"
        x-auth-type: "Application & Application User"
        x-throttling-tier: "Unlimited"
  securityDefinitions: 
    default: 
      type: "oauth2"
      authorizationUrl: "https://test.com"
      flow: "implicit"
      scopes: 
        LoginAndFTF: "Login And Fund Transfer"
      x-scopes-bindings: 
        LoginAndFTF: "LoginAndFTF"
  x-wso2-auth-header: "Authorization"
  x-wso2-cors: 
    corsConfigurationEnabled: false
    accessControlAllowOrigins: 
      - "*"
    accessControlAllowCredentials: false
    accessControlAllowHeaders: 
      - "authorization"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "SOAPAction"
    accessControlAllowMethods: 
      - "GET"
      - "PUT"
      - "POST"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
  x-wso2-production-endpoints: 
    urls: 
      - "http://192.168.1.228:8787/call"
    type: "http"
  x-wso2-sandbox-endpoints: 
    urls: 
      - "http://192.168.1.228:8787/call"
    type: "http"
  x-wso2-basePath: "/apiftf/1.0.0"
  x-wso2-transports: 
    - "http"
    - "https"
